Update xml_to_csv.yml

diff --git a/.github/workflows/xml_to_csv.yml b/.github/workflows/xml_to_csv.yml
--- a/.github/workflows/xml_to_csv.yml
+++ b/.github/workflows/xml_to_csv.yml
@@ -5,7 +5,6 @@ on:
     branches:
       - main
   schedule:
-    # Runs every 4 hours, adjusted for Estonian time (EEST, UTC+3)
     - cron: '0 1,5,9,13,17,21 * * *'
   workflow_dispatch:
 
@@ -14,7 +13,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: read
-      actions: write  # Add this if you are uploading artifacts
+      actions: write
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -33,10 +32,10 @@ jobs:
           python process_urls_to_csv.py
 
       - name: List generated CSV files
-        run: ls -l *.csv
+        run: ls -l *.csv || true # This will not fail the workflow if no files are found.
 
       - name: Upload processed CSV files as artifacts
-        uses: actions/upload-artifact@v4 # <<< UPDATED TO V4
+        uses: actions/upload-artifact@v4
         with:
           name: processed-catalogue-files
           path: "*.csv"
